default_install_hook_types:
- pre-commit
- commit-msg
- post-checkout
- post-merge
- post-rewrite

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff (lint)
        description: check if the changed files pass the ruff linter
        language: system
        entry: uv run ruff check
        types: [python]
        stages:
          - pre-commit

      - id: ruff-format
        name: ruff (format)
        description: check if the changed files pass the ruff formatter
        language: system
        entry: uv run ruff format
        types: [python]
        stages:
          - pre-commit

      - id: ruff-isort
        name: ruff (isort)
        description: check if the changed files pass the ruff import sorter
        language: system
        entry: uv run ruff check --select I --fix
        types: [python]
        stages:
          - pre-commit

      - id: mypy
        name: mypy
        description: check if the changed files pass the mypy type checker
        language: system
        entry: uv run mypy
        types: [python]
        stages:
          - pre-commit

      - id: uv-lock
        name: uv (lock)
        description: Automatically run 'uv lock' on your project dependencies
        entry: uv lock
        language: system
        files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        pass_filenames: false

      - id: uv-sync
        name: uv (sync)
        description: Automatically run 'uv sync' after pull, checkout and rebase
        entry: uv sync --no-active --locked
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - post-checkout
          - post-merge
          - post-rewrite

