[build-system]
requires = ["uv_build>=0.11.14,<0.12"]
build-backend = "uv_build"

[project]
name = "cimon"
version = "0.1.0"
description = "A ci monitoring tool"
readme = "README.md"
license = { text = "MIT" }
authors = [
    {name = "Ayhan Ueretmen", email = "ayhan.ueretmen@cariad.technology"},
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "click>=8.3.0",
    "cron-descriptor>=2.0.6",
    "pygithub>=2.8.1",
    "pyarrow>=21.0.0",
    "pydantic>=2.9.0",
    "pyyaml>=6.0.3",
    "textual>=8.2.7",
]

[project.scripts]
cimon = "cimon.__main__:main"

[project.optional-dependencies]
pandas = [
    "pandas>=2.2.0",
]

[dependency-groups]
dev = [
]
test = [
    "pytest~=9.0.0",
    "pytest-mock~=3.15.0",
    "pytest-cov>=7.1.0",
    "pytest-random-order>=1.2.0",
    "pytest-xdist>=3.8.0",
]
docs = [
    "properdocs~=1.6.0",
    "mike~=2.2.0",
    "mkdocs-material~=9.7.0",
    "mkdocstrings[python]~=1.0.0",
    "mkdocs-same-dir~=0.1.0",
]

[tool.git-changelog]
convention = "conventional"
provider = "github"
output = "CHANGELOG.md"

[tool.commitizen]
version_provider="pep621"
update_changelog_on_bump=false
